CREATE TABLE IF NOT EXISTS `annotations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `appId` varchar(255) DEFAULT NULL,
  `sessionId` varchar(255) DEFAULT NULL,
  `workerId` varchar(255) DEFAULT NULL,
  `itemId` varchar(255) DEFAULT NULL,
  `condition` varchar(255) DEFAULT NULL,
  `data` mediumtext,
  `preview_data` mediumtext,
  `status` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `verified` boolean DEFAULT FALSE,
  `code` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `task` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `taskMode` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_annotations_on_appId` (`appId`),
  KEY `index_annotations_on_sessionId` (`sessionId`),
  KEY `index_annotations_on_workerId` (`workerId`),
  KEY `index_annotations_on_itemId` (`itemId`),
  KEY `index_annotations_on_condition` (`condition`),
  KEY `index_annotations_on_status` (`status`),
  KEY `index_annotations_on_task` (`task`),
  KEY `index_annotations_on_created_at` (`created_at`),
  KEY `index_annotations_on_updated_at` (`updated_at`),
  KEY `index_annotations_on_type` (`type`)
);

CREATE TABLE IF NOT EXISTS `segment_annotations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `appId` varchar(255) DEFAULT NULL,
  `sessionId` varchar(255) DEFAULT NULL,
  `workerId` varchar(255) DEFAULT NULL,
  `modelId` varchar(255) DEFAULT NULL,
  `objectId` varchar(255) DEFAULT NULL,
  `segments` mediumtext,
  `label` varchar(255) DEFAULT NULL,
  `labelType` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `verified` boolean DEFAULT FALSE,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `annId` int(11) DEFAULT NULL,
  `condition` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_segment_annotations_on_appId` (`appId`),
  KEY `index_segment_annotations_on_sessionId` (`sessionId`),
  KEY `index_segment_annotations_on_workerId` (`workerId`),
  KEY `index_segment_annotations_on_modelId` (`modelId`),
  KEY `index_segment_annotations_on_label` (`label`),
  KEY `index_segment_annotations_on_labelType` (`labelType`),
  KEY `index_segment_annotations_on_status` (`status`),
  KEY `index_segment_annotations_on_condition` (`condition`),
  KEY `index_segment_annotations_on_annId` (`annId`)
);
