CREATE TABLE IF NOT EXISTS `segment_annotations_clean` (
  `id` int(11) NOT NULL,
  `appId` varchar(255) DEFAULT NULL,
  `sessionId` varchar(255) DEFAULT NULL,
  `workerId` varchar(255) DEFAULT NULL,
  `modelId` varchar(255) DEFAULT NULL,
  `objectId` varchar(255) DEFAULT NULL,
  `segments` mediumtext,
  `label` varchar(255) DEFAULT NULL,
  `labelType` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `verified` boolean DEFAULT FALSE,
  `created_at` timestamp NOT NULL,
  `updated_at` timestamp NOT NULL,
  `annId` int(11) DEFAULT NULL,
  `condition` varchar(255) DEFAULT NULL,
  `created_at_cleaned` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at_cleaned` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `index_segment_annotations_cleaned_on_appId` (`appId`),
  KEY `index_segment_annotations_cleaned_on_sessionId` (`sessionId`),
  KEY `index_segment_annotations_cleaned_on_workerId` (`workerId`),
  KEY `index_segment_annotations_cleaned_on_modelId` (`modelId`),
  KEY `index_segment_annotations_cleaned_on_label` (`label`),
  KEY `index_segment_annotations_cleaned_on_labelType` (`labelType`),
  KEY `index_segment_annotations_cleaned_on_status` (`status`),
  KEY `index_segment_annotations_cleaned_on_condition` (`condition`),
  KEY `index_segment_annotations_cleaned_on_annId` (`annId`)
);
